// <auto-generated />
using System;
using HRMS.Core.Entities.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMS.Core.Entities.Migrations
{
    [DbContext(typeof(HRMSContext))]
    partial class HRMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRMS.Core.Entities.Master.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 11, 6, 23, 49, 27, 938, DateTimeKind.Local).AddTicks(2658));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Department", "Master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Designation", "Master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SalaryHeads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<string>("HeadCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDependOnDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisplayOnPaySlip")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SalaryHeads", "Master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Payroll.EmployeeAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DateMonth")
                        .HasColumnType("int");

                    b.Property<int>("DateYear")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LOPDays")
                        .HasColumnType("int");

                    b.Property<int>("PresentDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attandence", "Payroll");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Payroll.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AadharCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternateMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiometricCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchOfficeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfMairrage")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESICNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESICPreviousNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationalQualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyRelationWithEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployementStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IJPLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Induction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsESICEligible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LandLineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveApprover1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveApprover2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeEmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAndFBankAccountNumberx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAndLHeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIPEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIPStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousOrganisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruitmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruitmentSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftTiming")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperVisorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupernationAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxFileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VISADate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VISANumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkExprience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDetail", "Payroll");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Payroll.EmployeeNonCTC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ARRVPF_Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsRecovery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BooksAndPeriodicalTaxable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CarMaintainenceTaxable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DateMonth")
                        .HasColumnType("int");

                    b.Property<int>("DateYear")
                        .HasColumnType("int");

                    b.Property<decimal>("EPFRecovery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<decimal>("FoodCouponDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GratuityPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoldSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("JoiningBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LabourWelfare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaveEncashment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MiscleneousDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MobileDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NPSEarning")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NoticePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NoticeRecovery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherRecovery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OverTimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ParentalMediclaim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerformaceLinkedPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerformanceIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerformanceLinkedPayB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryAdvanceDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StatuaryBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmployeeNonCTCComponent", "Payroll");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Payroll.EmployeeSalaryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BookAndPriodical")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CarRunningAndMaintainence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConvenanceAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ESIDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EducationAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("int");

                    b.Property<decimal>("FoodCouponAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseRentAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPFEligible")
                        .HasColumnType("bit");

                    b.Property<decimal>("LTARiembursement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LWFDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PACover")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PFDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PLP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PTStateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpecialAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TelephoneAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UniformReimburesement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmployeeSalaryDetail", "Payroll");
                });
#pragma warning restore 612, 618
        }
    }
}
